#!/usr/bin/env python3
"""Generate the wiki Projects catalog from the local filesystem, repos.json, and the Command Center."""
from __future__ import annotations

import json
import sys
from pathlib import Path

from bs4 import BeautifulSoup

SCAN_DIRS = {"apps": "app", "sites": "site", "agents": "agent"}


def scan_repos(base_dir: Path) -> list[dict]:
    repos = []
    for sub, type_ in SCAN_DIRS.items():
        d = base_dir / sub
        if not d.is_dir():
            continue
        for child in sorted(d.iterdir()):
            if (child / ".git").exists():
                repos.append({"name": child.name, "type": type_, "path": f"{sub}/{child.name}"})
    return repos


def load_manifest(repos_json_path: Path) -> dict:
    if not repos_json_path.is_file():
        return {}
    data = json.loads(repos_json_path.read_text(encoding="utf-8"))
    return {r["name"]: r for r in data.get("repositories", [])}


def load_card_map(card_map_path: Path) -> dict:
    if not card_map_path.is_file():
        return {}
    return json.loads(card_map_path.read_text(encoding="utf-8"))


def parse_command_center(index_html_path: Path) -> dict:
    if not index_html_path.is_file():
        return {}
    soup = BeautifulSoup(index_html_path.read_text(encoding="utf-8"), "html.parser")
    cards = {}
    for card in soup.select("a.card"):
        id_el = card.select_one(".card-id")
        if not id_el:
            continue
        card_id = id_el.get_text(strip=True).split("//")[0].strip()
        meta_el = card.select_one(".card-meta")
        meta = meta_el.get_text(strip=True) if meta_el else ""
        version = date = status = None
        if meta.upper() == "LIVE":
            status = "live"
        elif meta.startswith("v") and "·" in meta:
            ver_part, _, date_part = meta.partition("·")
            version = ver_part.strip().lstrip("v")
            date = date_part.strip()
            status = "active"
        name_el = card.select_one(".card-name")
        url_el = card.select_one(".card-url")
        desc_el = card.select_one(".card-desc")
        cards[card_id] = {
            "display_name": name_el.get_text(strip=True) if name_el else None,
            "url": url_el.get_text(strip=True) if url_el else None,
            "description": desc_el.get_text(strip=True) if desc_el else None,
            "version": version,
            "date": date,
            "status": status,
        }
    return cards


def read_description(repo_path: Path) -> str:
    readme = repo_path / "README.md"
    if not readme.is_file():
        return ""
    for line in readme.read_text(encoding="utf-8").splitlines():
        s = line.strip()
        if s and not s.startswith("#") and not s.startswith("!["):
            return s
    return ""


def github_web_url(clone_url: str | None) -> str | None:
    if not clone_url:
        return None
    return clone_url[:-4] if clone_url.endswith(".git") else clone_url


def enrich(repos: list[dict], manifest: dict, cards: dict, card_map: dict, base_dir: Path) -> list[dict]:
    enriched = []
    for repo in repos:
        name = repo["name"]
        m = manifest.get(name, {})
        card_id = card_map.get(name)
        card = cards.get(card_id, {}) if card_id else {}
        description = card.get("description") or read_description(base_dir / repo["path"]) or "No description."
        enriched.append({
            **repo,
            "github": m.get("github"),
            "in_manifest": name in manifest,
            "display_name": card.get("display_name") or name,
            "version": card.get("version"),
            "date": card.get("date"),
            "status": card.get("status"),
            "url": card.get("url"),
            "description": description,
        })
    return enriched


def detect_drift(repos: list[dict], manifest: dict, base_dir: Path) -> list[str]:
    warnings = []
    scanned = {r["name"] for r in repos}
    for name in sorted(scanned):
        if name not in manifest:
            warnings.append(f"on disk but missing from repos.json: {name}")
    for name, m in sorted(manifest.items()):
        target = m.get("targetDirectory", "")
        if target.split("/")[0] in SCAN_DIRS and not (base_dir / target).is_dir():
            warnings.append(f"in repos.json but not on disk: {name} ({target})")
    return warnings


def render_index(projects: list[dict]) -> str:
    lines = [
        "# Projects",
        "",
        "_Auto-generated by `scripts/gen_catalog.py` — do not edit by hand._",
        "",
        "| Project | Type | Version | Status | Repo |",
        "| --- | --- | --- | --- | --- |",
    ]
    for p in sorted(projects, key=lambda x: (x["type"], x["name"])):
        ver = f"v{p['version']}" if p["version"] else "—"
        status = p["status"] or "—"
        web = github_web_url(p["github"])
        repo_cell = f"[GitHub]({web})" if web else "—"
        name_cell = f"[{p['display_name']}]({p['name']}.md)"
        lines.append(f"| {name_cell} | {p['type']} | {ver} | {status} | {repo_cell} |")
    lines.append("")
    return "\n".join(lines)


def render_project_page(p: dict) -> str:
    lines = [f"# {p['display_name']}", ""]
    if p["display_name"].lower() != p["name"].lower():
        lines += [f"`{p['name']}`", ""]
    lines += [p["description"], "", "| Field | Value |", "| --- | --- |", f"| Type | {p['type']} |"]
    if p["version"]:
        lines.append(f"| Version | v{p['version']} |")
    if p["date"]:
        lines.append(f"| Updated | {p['date']} |")
    if p["status"]:
        lines.append(f"| Status | {p['status']} |")
    if p["url"]:
        lines.append(f"| Live | https://{p['url']} |")
    web = github_web_url(p["github"])
    if web:
        lines.append(f"| Repo | {web} |")
    lines.append(f"| Local path | `{p['path']}` |")
    lines.append("")
    return "\n".join(lines)
